.github/workflows/test.yml, integration-tests/MyTestDirectory.ts, integration-tests/cypress/e2e/blink-ripgrep/basic_spec.cy.ts, integration-tests/test-environment/other-file.lua, integration-tests/test-environment/other-file.txt, lua/blink-ripgrep/init.lua, lua/blink-ripgrep/ripgrep_parser.lua
This does not seem to work on neovim stable right now. For now I'm dropping support for stable.
=> feat!: highlight the match context with treesitter

lua/blink-ripgrep/init.lua, spec/blink-ripgrep/get_prefix_spec.lua
Previously, only words that consisted of letters, numbers, underscores, and dashes were matched. This change allows for words that include special word like characters such as
- umlauts (e.g. 'ö', 'ä', 'å', 'ü')
- accented characters (e.g. 'é', 'ç', 'ñ', 'ü')
- Cyrillic characters (e.g. 'к', 'о', 'с', 'м')
- Chinese characters (e.g. '你', '好')
- Japanese characters (e.g. '日', '本', '語')
- Korean characters (e.g. '한', '국', '어')
- Greek characters (e.g. 'τ', 'ο', 'π', 'ι', 'κ', 'ή')
- emoji (e.g. '😄', '👍', '👎')
=> feat: can find words that include special characters

.github/workflows/test.yml, README.md, integration-tests/cypress.config.ts, lua/blink-ripgrep/init.lua
By default, ripgrep will search all files in the project, which can be slow if there are large files. Now, files larger than 1 megabyte are skipped from the search altogether by default. This can be customized with the `max_filesize` option in the `blink-ripgrep` configuration.
The possible values are determined by ripgrep itself. Examples:
- "1024" (bytes by default)
- "200K"
- "1M"
- "999G" (effectively opts out of ignoring any files)
=> feat(performance): max_filesize option (def: 1M) skips large files

.github/workflows/test.yml, integration-tests/package.json, pnpm-lock.yaml
Previously this caused the first 1-2 tests to fail, although this was always caught by retries. It's not very clean to have these failures, so let's be clear and install all neovim plugins beforehand.
=> ci: preinstall neovim plugins before integration-tests

lua/blink-ripgrep/init.lua
Right now we are registering each match multiple times, which is not very useful. It will add more context to the context window (documentation), but it's not very clear to read the context anyway. Most of the time I just ignore it.
If in the future we have a better way to inspect each submatch, this should be reconsidered.
=> perf: only register each unique match once

lua/blink-ripgrep/init.lua, lua/blink-ripgrep/ripgrep_parser.lua, package.json, spec/blink-ripgrep/ripgrep_parser_spec.lua
Issue
=====
The current implementation of the ripgrep parser includes all the lines that matched in each file, and displays the same lines for each match. As a user, I'm interested in the context around the match, not the entire file. This is especially important when the file is large, and the file contains a lot of matches.
Lots of unnecessary work is being done in this case.
Solution
========
Only include the necessary context preview for each match. This will reduce the memory usage and hopefully make the plugin faster.
The speed could still be better in huge repos, but this is a step in the right direction.
=> perf: only collect the necessary context preview for each match

lua/blink-ripgrep/init.lua, lua/blink-ripgrep/ripgrep_parser.lua, spec/blink-ripgrep/ripgrep_parser_spec.lua
blink should display each word only once, since it's not useful to display copies. Most often the user wants to find and reuse a word in their project, but it does not matter where the word is found.
We can maybe save some resources by skipping words that we have already gotten from ripgrep's output.
=> perf: skip processing result words that already exist

integration-tests/test-environment/.config/nvim/init.lua, lua/blink-ripgrep/init.lua
Solves https://github.com/mikavilpas/blink-ripgrep.nvim/issues/52
=> fix: crash when no options are provided

README.md, integration-tests/MyTestDirectory.ts, lua/blink-ripgrep/init.lua, spec/blink-ripgrep/get_command_spec.lua
This can help in adjusting performance in specific situations. A "batteries included" experience is provided by default, but specific situations might benefit from additional options.
=> feat: allow passing `additional_rg_options` to ripgrep

lua/blink-ripgrep/init.lua, package.json
Fixes https://github.com/mikavilpas/blink-ripgrep.nvim/issues/53
=> fix: random blink crash due to E5560 (fast event context)

README.md, integration-tests/MyTestDirectory.ts, integration-tests/cypress/e2e/blink-ripgrep/basic_spec.cy.ts, integration-tests/test-environment/.config/nvim/init.lua, integration-tests/test-environment/limited/subproject/example.clj, lua/blink-ripgrep/init.lua, lua/blink-ripgrep/ripgrep_parser.lua
When a result is found for a file whose filetype does not have a
treesitter parser installed, fall back to regex based highlighting that
is bundled in Neovim. This allows highlighting many more file types out
of the box.
See here for the blink side implementation and a mini demo:
https://github.com/Saghen/blink.cmp/pull/650
=> feat: fall back to regex highlighting when treesitter not available

README.md, lua/blink-ripgrep/init.lua, spec/blink-ripgrep/get_command_spec.lua
Previously, the project root was always assumed to be the nearest directory containing a `.git` directory. This commit introduces a new `project_root_marker` option that allows users to configure how the project root is found.
This option accepts the same arguments as the marker given to `:h vim.fs.root()` which offers many possibilities for configuration. The default value is still `.git`.
Closes #59
=> feat: allow flexible configuration of the project root

README.md, integration-tests/cypress/e2e/blink-ripgrep/basic_spec.cy.ts, integration-tests/test-environment/.config/nvim/init.lua, lua/blink-ripgrep/highlighting.lua, lua/blink-ripgrep/init.lua, lua/blink-ripgrep/ripgrep_parser.lua, spec/blink-ripgrep/ripgrep_parser_spec.lua
When a match has been found in a file in the project, the documentation
window should show a preview of the match context (lines around the
match), and highlight the part where the match was found. This way the
user can quickly get an idea of where the match was found.
By default, the match is highlighted with the `BlinkRipgrepMatch`
highlight group, which is linked to (looks like) the `Search` highlight
group.
https://github.com/user-attachments/assets/0bc7485e-4140-4f85-9fa3-54b0ff88f3d0
=> feat: highlight the match in the documentation window

README.md
Blink changed the manual invocation option from `sources` to `providers`.
=> Change sources to providers

README.md, integration-tests/test-environment/.config/nvim/init.lua, lua/blink-ripgrep/init.lua
BREAKING CHANGE: The label will no longer show "(rg)" by default for blink-ripgrep results. If you want to preserve the previous behavior, you can copy the `transform_items` option from the README to your configuration.
It's much better to do it this way because
- not all users like it
- it can also be used to customize other display aspects of the results
- blink uses a different color for the label description, so it's even easier to distinguish the results
Adding a  custom description looks like this
Closes https://github.com/mikavilpas/blink-ripgrep.nvim/issues/64
=> feat!: don't show "(rg)" in the label by default

README.md, integration-tests/MyTestDirectory.ts, integration-tests/cypress/e2e/blink-ripgrep/basic_spec.cy.ts, integration-tests/package.json, integration-tests/test-environment/.config/nvim/init.lua, integration-tests/test-environment/config-modifications/don't_use_debug_mode.lua, lua/blink-ripgrep/init.lua, lua/blink-ripgrep/ripgrep_command.lua, pnpm-lock.yaml, spec/blink-ripgrep/get_command_spec.lua
Issue
=====
It's difficult to diagnose performance issues with the plugin. Some
users have unfortunately run into this in
https://github.com/mikavilpas/blink-ripgrep.nvim/issues/82
Solution
========
Add a `debug` option to the plugin configuration that prints the rg
command that was used to get completions. The user can then copy paste
the command into their terminal and play around with it.
By default it's off, but can be enabled by setting `debug = true`.
=> feat: add a debug mode that prints the rg command that was used

integration-tests/MyTestDirectory.ts, integration-tests/cypress/e2e/blink-ripgrep/basic_spec.cy.ts, integration-tests/test-environment/limited/dir with spaces/file with spaces.txt, integration-tests/test-environment/limited/dir with spaces/other file with spaces.txt, lua/blink-ripgrep/init.lua, lua/blink-ripgrep/ripgrep_command.lua
Issue
=====
When working in a project whose project_root_marker path contained space characters (maybe even other special characters), the plugin would not provide any completions.
This was caused by extra escaping of the path in the command that was run in the background.
Solution
========
Correctly escape the spaces and provide completions.
test: can run the debug command in a shell
=> fix: not providing completions for a project root with spaces

integration-tests/cypress/e2e/blink-ripgrep/basic_spec.cy.ts
The first test was failing because sometimes blink takes its time in showing completions.
=> test: wait for blink to show up in the first test

integration-tests/cypress/e2e/blink-ripgrep/basic_spec.cy.ts, integration-tests/test-environment/.config/nvim/init.lua, lua/blink-ripgrep/init.lua, lua/blink-ripgrep/visualization.lua
Issue
=====
It's hard to understand when exactly ripgrep is called to find matching words in the project. This is an important concern because of performance - ripgrep can take a long time to search through a large project.
Solution
========
Temporarily highlight the search prefix when a new ripgrep search is started. This will help users and maintainers understand the behavior of the plugin.
To enable this feature, set `debug` to `true` in the configuration. It's recommended to only enable this feature when debugging the plugin.
=> feat(debug,opt-in): temporarily highlight the search prefix

integration-tests/cypress/e2e/blink-ripgrep/basic_spec.cy.ts, lua/blink-ripgrep/init.lua
This only currently applies when blink finds some initial results. Otherwise each consecutive keypress will start a new search (this is the behavior before this commit).
=> test: make sure that only one ripgrep invocation is started

README.md, integration-tests/cypress/support/tui-sandbox.ts, integration-tests/package.json, integration-tests/test-environment/.config/nvim/init.lua, lua/blink-ripgrep/init.lua, pnpm-lock.yaml, vim.toml
Issue
=====
When typing text, if there are no matches for a ripgrep search, each
keypresses starts a new ripgrep search. This can lead to many searches
being active at the same time. This takes up resources and is not useful
(if the word did not match previously, it will never match with a longer
search string).
Solution
========
Stop previously running searches when a new search is started. This is
currently disabled by default (soft launch). To opt in, see the README.
If this works well for some time, it might become the default in the
future.
=> feat(opt-in): kill previous searches when a new search is started

README.md, integration-tests/cypress/e2e/blink-ripgrep/basic_spec.cy.ts, integration-tests/test-environment/.config/nvim/init.lua, lua/blink-ripgrep/init.lua
This supersedes the previous `future_features` version of kill_previous_searches. That should be removed, as this is now the default.
Closes https://github.com/mikavilpas/blink-ripgrep.nvim/issues/102
=> perf: kill previous ripgrep searches when a new search is started

README.md, integration-tests/MyTestDirectory.ts, integration-tests/cypress/e2e/blink-ripgrep/basic_spec.cy.ts, integration-tests/test-environment/config-modifications/disable_project_root_fallback.lua, integration-tests/test-environment/config-modifications/use_not_found_project_root.lua, lua/blink-ripgrep/init.lua, lua/blink-ripgrep/ripgrep_command.lua, spec/blink-ripgrep/get_command_spec.lua
This was originally authored by @joshzcold in https://github.com/mikavilpas/blink-ripgrep.nvim/pull/104
I did a couple of other things in between and decided to start a new branch to simplify porting the changes over to the latest version. The logic should be 100% the same though.
=> feat: allow canceling the search with `project_root_fallback = false`

README.md, integration-tests/MyTestDirectory.ts, integration-tests/cypress/e2e/blink-ripgrep/toggling.cy.ts, integration-tests/test-environment/.config/nvim/init.lua, integration-tests/test-environment/config-modifications/enable_toggling.lua, lua/blink-ripgrep/init.lua
Issue
=====
In some scenarios it's not nice to have blink-ripgrep pop up:
- if there are performance issues
- when giving a presentation
- when recording a video demo
Solution
========
Provide a way to toggle the plugin on/off with a keymap. Right now this is off by default and depends on
https://github.com/folke/snacks.nvim/blob/main/docs/toggle.md
Users that don't want to use this feature or add snacks.nvim can simply ignore it.
=> feat: enable toggling the plugin on/off with folke/snacks.nvim

lua/blink-ripgrep/init.lua
This api will replace the current `render` api in a future release of blink.
https://github.com/Saghen/blink.cmp/issues/1113
=> refactor: support new documentation rendering API (`draw`)

integration-tests/MyTestDirectory.ts, integration-tests/cypress/e2e/blink-ripgrep/toggling.cy.ts, integration-tests/test-environment/.config/nvim/init.lua, integration-tests/test-environment/config-modifications/enable_toggling.lua, lua/blink-ripgrep/init.lua, lua/blink-ripgrep/toggles.lua
Issue
=====
Enabling the toggling feature requires a manual setup call. It's difficult to do in a clean way that avoids duplicating the config.
Solution
========
Simplify the initialization and remove the ability to change the toggling configuration after the initial load. I think that's not a very useful feature anyway.
=> fix: complicated initialization of the toggling feature

lua/blink-ripgrep/backends/ripgrep/ripgrep.lua, lua/blink-ripgrep/backends/ripgrep/ripgrep_parser.lua, lua/blink-ripgrep/documentation.lua, lua/blink-ripgrep/highlighting.lua, spec/blink-ripgrep/documentation_spec.lua, spec/blink-ripgrep/ripgrep_parser_spec.lua
This should not be a breaking change, but please report any issues.
The motivation for this change is:
- I started to add a backend for git grep, but it does not support getting a context for matches like ripgrep does.
- In many cases, it is wasteful to render the context preview for every match anyway, because there might be 50 matches, and the user might look at only 0-3 of them
- The performance on my machine with this style was good
=> refactor!: render the context preview lazily, not immediately

README.md, integration-tests/MyTestDirectory.ts, integration-tests/cypress/e2e/blink-ripgrep/backend_gitgrep_spec.cy.ts, integration-tests/cypress/e2e/blink-ripgrep/backend_ripgrep_spec.cy.ts, integration-tests/cypress/e2e/blink-ripgrep/createFakeGitDirectoriesToLimitRipgrepScope.ts, integration-tests/cypress/e2e/blink-ripgrep/debug-mode.cy.ts, integration-tests/cypress/e2e/blink-ripgrep/verifyGitGrepBackendWasUsedInTest.ts, integration-tests/test-environment/config-modifications/use_gitgrep_backend.lua, lua/blink-ripgrep/backends/git_grep/git_grep.lua, lua/blink-ripgrep/backends/git_grep/git_grep_parser.lua, lua/blink-ripgrep/backends/git_grep/gitgrep_command.lua, lua/blink-ripgrep/backends/ripgrep/ripgrep.lua, lua/blink-ripgrep/backends/ripgrep/ripgrep_command.lua, lua/blink-ripgrep/backends/ripgrep/ripgrep_parser.lua, lua/blink-ripgrep/documentation.lua, lua/blink-ripgrep/highlighting.lua, lua/blink-ripgrep/init.lua
Issue
=====
The performance in huge repositories like
https://github.com/llvm/llvm-project is extremely slow. It takes ripgrep about a minute to search through the entire codebase before any completion suggestions are shown.
Solution
========
Provide a much faster alternative backend that uses `git grep` to search the codebase. This is still beta quality, but I think it can be improved incrementally to be pretty good.
This backend has the following benefits and drawbacks:
Benefits:
- much faster (5 seconds instead of 1 minute in llvm-project)
Drawbacks:
- does not work in non-git repositories
- not very configurable yet, but can be improved
- no way to ignore files based on their size like with ripgrep
Please provide feedback on this! I would like to add good support and tests for
- git …
=> feat(git,opt-in): experimental git grep backend

integration-tests/cypress/e2e/blink-ripgrep/verifyGitGrepBackendWasUsedInTest.ts, integration-tests/test-environment/config-modifications/use_gitgrep_backend.lua, lua/blink-ripgrep/init.lua
BREAKING CHANGE: If you were using the git_grep backend, you will need to update your configuration to use the new format.
Issue
=====
It's possible to choose between different backends (ripgrep and gitgrep) for the plugin. However, not all configuration options can be supported for all backends. Right now there are many ripgrep specific options that are confusing.
Solution
========
Change the backend configuration to use a table instead of a string. Later on, we can add more configuration options for each backend.
=> refactor!(future): change backend configuration to use a table

.gitignore, integration-tests/test-environment/.config/nvim/init.lua
=> test: bump blink.cmp version from 0.10.0 to 0.13.1

README.md, integration-tests/MyTestDirectory.ts, integration-tests/cypress/e2e/blink-ripgrep/backend_gitgrep_or_ripgrep_spec.cy.ts, integration-tests/cypress/e2e/blink-ripgrep/backend_gitgrep_spec.cy.ts, integration-tests/cypress/e2e/blink-ripgrep/debug-mode.cy.ts, integration-tests/cypress/e2e/blink-ripgrep/verifyGitGrepBackendWasUsedInTest.ts, integration-tests/test-environment/config-modifications/use_gitgrep_or_ripgrep_backend.lua, lua/blink-ripgrep/backends/git_grep_or_ripgrep/git_grep_or_ripgrep.lua, lua/blink-ripgrep/init.lua
Issue
=====
Currently, the plugin supports using ripgrep or gitgrep. It allows opting into more performance (gitgrep), or a solution that also works outside of git repositories.
This has to be configured before starting Neovim. However, sometimes users need to edit files in both types of projects. This requires manual work to keep the plugin working.
Solution
========
Add a new `gitgrep-or-ripgrep` backend. It uses gitgrep if the current directory is a git repository, otherwise it uses ripgrep.
Right now the backend is selected based on Neovim's current working directory (cwd). Feedback on this is welcome.
=> feat: allow using gitgrep or ripgrep based on the current directory

lua/blink-ripgrep/backends/git_grep/git_grep.lua, lua/blink-ripgrep/backends/git_grep_or_ripgrep/git_grep_or_ripgrep.lua, package.json
Issue
=====
GitGrepOrRipgrepBackend checks if the current directory is a git
repository with a shell command. If this shell command takes a long time
to execute, it will block the main thread, making the UI unresponsive.
Solution
========
Use blink.cmp.lib.async.task and avoid waiting for the shell command to
finish in a blocking manner. This allows the user to keep making edits
in neovim while the shell command is running.
It might be possible to also cancel the task cleanly, but I did not
really test this extensively.
=> Async improvements

README.md, lua/blink-ripgrep/backends/git_grep/git_grep.lua, lua/blink-ripgrep/backends/ripgrep/ripgrep.lua, lua/blink-ripgrep/init.lua
This disables documentation rendering completely, but avoids errors like:
> Error: ...al/nvim-data/lazy/blink.cmp/lua/blink/cmp/fuzzy/init.lua:44: can't serialize object of type 6
> Nvim v0.11.0
> blink.cmp v1.0.0
> blink-ripgrep commit af61f99
https://github.com/mikavilpas/blink-ripgrep.nvim/issues/185
=> feat: add workaround for issue with documentation

README.md
Closes https://github.com/mikavilpas/blink-ripgrep.nvim/issues/186
=> docs: update the structure of the `backend` option in the README

README.md, integration-tests/cypress.config.ts, integration-tests/cypress/e2e/blink-ripgrep/backend_gitgrep_spec.cy.ts, integration-tests/cypress/e2e/blink-ripgrep/backend_ripgrep_spec.cy.ts, integration-tests/cypress/e2e/blink-ripgrep/debug-mode.cy.ts, integration-tests/cypress/support/tui-sandbox.ts, integration-tests/package.json, integration-tests/test-environment/.config/nvim/init.lua, lua/blink-ripgrep/backends/git_grep/git_grep.lua, lua/blink-ripgrep/init.lua, lua/blink-ripgrep/toggles.lua, pnpm-lock.yaml
Introduced in https://github.com/mikavilpas/blink-ripgrep.nvim/pull/123
and https://github.com/mikavilpas/blink-ripgrep.nvim/pull/127
https://github.com/mikavilpas/blink-ripgrep.nvim/actions/runs/14086700119/job/39452573012?pr=183
=> feat: move toggle keymaps to stable features

README.md, lua/blink-ripgrep/backends/git_grep/git_grep.lua, lua/blink-ripgrep/backends/ripgrep/ripgrep.lua, lua/blink-ripgrep/init.lua
The issue has now been resolved in blink, so we can safely remove the workaround.
https://github.com/mikavilpas/blink-ripgrep.nvim/issues/185#issuecomment-2847654332
=> feat: remove issue185_workaround as it is no longer needed

lua/blink-ripgrep/backends/git_grep/git_grep.lua, lua/blink-ripgrep/backends/ripgrep/ripgrep.lua
In https://github.com/Saghen/blink.cmp/issues/1113 (2025-25-02), the `render` function was deprecated in favor of the `draw` function.
The old `render` function was kept around to give users some time to upgrade, but it's been so long that it's time to remove it.
=> refactor: remove deprecated render function

lua/blink-ripgrep/init.lua
This accomplishes the same thing,
- but opts into having the blink framework handle the disabling, which might be useful in the future.
- is more in line with the other sources
https://cmp.saghen.dev/development/source-boilerplate.html
=> refactor: handle disabling with `source:enabled()`

lua/blink-ripgrep/backends/git_grep/git_grep.lua, lua/blink-ripgrep/backends/ripgrep/ripgrep.lua
It's not present according to the types, which means it shouldn't be there.
=> refactor: remove `context` field from `resolve()` calls

README.md, integration-tests/cypress/e2e/blink-ripgrep/toggling.cy.ts, integration-tests/test-environment/.config/nvim/init.lua, lua/blink-ripgrep/init.lua, lua/blink-ripgrep/toggles.lua
This is probably only useful for plugin developers.
I have had some visual issues come up occasionally. I typically don't
have time to investigate them, and I either forget to do it later when I
have time, or cannot reproduce them any longer.
This commit adds a toggle to turn debug mode on and off, so that I can
quickly enable it when I see a visual issue, and then disable it again
when I am done debugging.
=> feat(opt-in): toggle debug mode on/off for quick plugin debugging

README.md, integration-tests/cypress/e2e/blink-ripgrep/backend_gitgrep_spec.cy.ts, integration-tests/cypress/e2e/blink-ripgrep/searching-inside-projects.cy.ts, integration-tests/cypress/e2e/blink-ripgrep/utils/verifyGitGrepBackendWasUsedInTest.ts, integration-tests/test-environment/.config/nvim/init.lua, integration-tests/test-environment/config-modifications/apply_highlight_customization.lua, integration-tests/test-environment/config-modifications/disable_project_root_fallback.lua, integration-tests/test-environment/config-modifications/set_ignore_paths.lua, integration-tests/test-environment/config-modifications/use_additional_paths.lua, integration-tests/test-environment/config-modifications/use_case_sensitive_search.lua, integration-tests/test-environment/config-modifications/use_gitgrep_backend.lua, integration-tests/test-environment/config-modifications/use_gitgrep_or_ripgrep_backend.lua, lua/blink-ripgrep/backends/git_grep/git_grep.lua, lua/blink-ripgrep/backends/ripgrep/ripgrep.lua, lua/blink-ripgrep/backends/ripgrep/ripgrep_command.lua, lua/blink-ripgrep/documentation.lua, lua/blink-ripgrep/init.lua, lua/blink-ripgrep/migrate_config.lua, lua/blink-ripgrep/types/legacy_options.lua, spec/blink-ripgrep/config_spec.lua, spec/blink-ripgrep/get_command_spec.lua
**Issue:**
Currently, two backends are supported: `ripgrep` and `gitgrep` (a
fallback backend `gitgrep-or-ripgrep` is also available). These use
ripgrep (`rg`) and `git grep` respectively to search for matches.
However, the configuration options for these backends are not clearly
separated, leading to confusion about which options apply to which
backend.
**Solution:**
Move to a new configuration format that clearly separates the
configuration options for each backend.
```lua
-- old config format
RgSource.config = {
prefix_min_len = 3,
fallback_to_regex_highlighting = true,
project_root_marker = ".git",
context_size = 5,                -- moved to backend config
max_filesize = "1M",             -- moved to backend.ripgrep config
additional_rg_options = {},      -- moved to backend.ripgrep …
```
=> refactor!: clearly support backend specific options

integration-tests/package.json, integration-tests/test-environment/.config/nvim/init.lua, lua/blink-ripgrep/backends/git_grep/git_grep.lua, lua/blink-ripgrep/backends/ripgrep/ripgrep.lua, pnpm-lock.yaml
It's confusing for users to see `RipgrepGit` and `RipgrepRipgrep` as
kind names. This commit renames them to `Git` and `Ripgrep`
respectively.
Closes https://github.com/mikavilpas/blink-ripgrep.nvim/issues/265
This makes it easier to see if they change, or if they look weird.
=> fix: make `kind_name` less technical

integration-tests/cypress/e2e/blink-ripgrep/backend_gitgrep_or_ripgrep_spec.cy.ts, integration-tests/cypress/e2e/blink-ripgrep/backend_gitgrep_spec.cy.ts, integration-tests/cypress/e2e/blink-ripgrep/backend_ripgrep_spec.cy.ts, integration-tests/cypress/e2e/blink-ripgrep/utils/textIsVisibleWithColor.ts
Apparently it does not cause issues when running all tests headlessly,
which is done in ci.
=> Test improvements

.github/workflows/test.yml, lua/blink-ripgrep/backends/git_grep/git_grep.lua, lua/blink-ripgrep/backends/git_grep/git_grep_parser.lua, lua/blink-ripgrep/backends/ripgrep/ripgrep.lua, lua/blink-ripgrep/backends/ripgrep/ripgrep_parser.lua
https://github.com/actions/upload-artifact/blob/de65e23aa2b7e23d713bb51fbfcb6d502f8667d8/README.md?plain=1#L125
Closes https://github.com/mikavilpas/blink-ripgrep.nvim/issues/278
=> refactor: remove `prefix` from git_grep and ripgrep files as unused

README.md
Dev and testing dependencies of the plugin are updated frequently. This does not benefit end users at all, so recommend pinning to the latest stable version instead. It can get annoying to get a useless update every day.
=> docs: recommend pinning to `version = "*"` to avoid frequent updates
